# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  repo: '$(build.repository.name)'

steps:
- script: |
    ls -altGr $(repo)
  displayName: 'List repo'

- task: GoTool@0
  inputs:
    version: '1.14.3'
  displayName: 'Install Go 1.14.3'

- script: |
    go version
  displayName: 'Go Version'
