# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  repo: '$(build.repository.name)'

steps:
- task: GoTool@0
  inputs:
    version: '1.14.3'
  displayName: 'Install Go 1.14.3'

- script: |
    go mod download
  displayName: 'Download dependencies'

- script: |
    go test -v ./...
  displayName: 'Run tests'

- script: |
    go build cmd/msgcommitter/main.go

- script: |
    ls -altGr .
  displayName: 'List current dir'
